services:
  - type: web
    name: goose-kixie-api
    env: docker
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        value: sqlite:////data/goose_kixie.db
      - key: REALNEX_API_BASE
        value: https://sync.realnex.com/api/v1/Crm
      - key: APP_SIGNING_KEY
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: BASE_URL
        sync: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
